//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalsOperations
    {
        public int GoalOperationId { get; set; }
        public int OperationId { get; set; }
        public string Comment { get; set; }
        public int GoalId { get; set; }
    
        public virtual Goals Goals { get; set; }
        public virtual Operations Operations { get; set; }
    }
}
