//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoneyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goals()
        {
            this.GoalsOperations = new HashSet<GoalsOperations>();
        }
    
        public int GoalId { get; set; }
        public int UserId { get; set; }
        public string GoalName { get; set; }
        public Nullable<int> GoalSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalsOperations> GoalsOperations { get; set; }
    }
}
